### ISSUE TITLE
Default minimap2 parameters

### ISSUE THREAD

**Issue by schellt** [BGI-Qingdao/TGS-GapCloser#11]
Dear Lidong,
I recognized that you automatically set the minimap2 parameters according `--tgstype` which are `-x ava-ont` and `-x ava-pb` for Nanopore and PacBio reads respectively.
Can you explain why you don't use the options `-x map-ont` and `-x map-pb`?
Furthermore the option `-H` should be used preferrable for PacBio according to the manual. Do you have a reason for not specifying this option?
Thank you very much.
Best regards,
Tilman

**Comment by cchd0001** [comment]
Hi Tilman

Please see #8  about why we use ```ava-ont``` and ```-x ava-pb``` instead of  ```-x map-ont``` and ```-x map-pb``` .

We tested  ```-H``` option in small test data and see little effect .  Could you share with us if your test shows different results,

Best wishes 
Lidong Guo

**Comment by schellt** [comment]
Dear Lidong,
sorry that I didn't checked the issues before opening this one completely.
I find your arguments in #8 completely valid. I always use the `-H` option for PacBio reads because it's recommended by the authors. I don't have any experience if this option has a high impact on mapping rate or alignment quality.
Best regards,
Tilman
