### ISSUE TITLE
Racon polishing correct?

### ISSUE THREAD

**Issue by schellt** [BGI-Qingdao/TGS-GapCloser#12]
Dear Lidong,
I executed TGS-GapCloser as follows:
`TGS-GapCloser.sh --scaff scaffolds.fasta --reads pacbio.fa --output gapclose --racon /path/to/racon-1.4.3/build/bin/racon --tgstype pb --thread 64`

According to the exit status the execution was successful but when I check the STDERR, there are following errors:
```
/path/to/TGS-GapCloser-release_v1.0.1/TGS-GapCloser.sh: line 490: 48470 Illegal instruction     (core dumped) $RACON -t $THREAD $TGS_READS $OUT_PREFIX.$curr_tag.paf $OUT_PREFIX.ont.$curr_tag.fasta > $OUT_PREFIX.ont.$curr_tag.racon.fasta 2> $OUT_PREFIX.$curr_tag.racon.log
/path/to/TGS-GapCloser-release_v1.0.1/TGS-GapCloser.sh: line 490: 15978 Illegal instruction     (core dumped) $RACON -t $THREAD $TGS_READS $OUT_PREFIX.$curr_tag.paf $OUT_PREFIX.ont.$curr_tag.fasta > $OUT_PREFIX.ont.$curr_tag.racon.fasta 2> $OUT_PREFIX.$curr_tag.racon.log
/path/to/TGS-GapCloser-release_v1.0.1/TGS-GapCloser.sh: line 490: 48472 Illegal instruction     (core dumped) $RACON -t $THREAD $TGS_READS $OUT_PREFIX.$curr_tag.paf $OUT_PREFIX.ont.$curr_tag.fasta > $OUT_PREFIX.ont.$curr_tag.racon.fasta 2> $OUT_PREFIX.$curr_tag.racon.log
```

Do you think that these errors harmful?
The file `gapclose.racon.log` looks fine to me:
```
[racon::Polisher::initialize] loaded target sequences 1.372103 s
[racon::Polisher::initialize] loaded sequences 1382.637417 s
[racon::Polisher::initialize] loaded overlaps 1474.567420 s
[racon::Polisher::initialize] aligning overlaps [====================] 592.444451 s
[racon::Polisher::initialize] transformed data into windows 18.428096 s
[racon::Polisher::initialize] loaded target sequences 1.362661 s
[racon::Polisher::initialize] loaded sequences 1342.986217 s
[racon::Polisher::initialize] loaded overlaps 1453.761094 s
[racon::Polisher::initialize] aligning overlaps [====================] 571.474114 s
[racon::Polisher::initialize] transformed data into windows 19.142867 s
[racon::Polisher::initialize] loaded target sequences 1.428398 s
[racon::Polisher::initialize] loaded sequences 1361.938485 s
[racon::Polisher::initialize] loaded overlaps 1298.255777 s
[racon::Polisher::initialize] aligning overlaps [====================] 532.658983 s
[racon::Polisher::initialize] transformed data into windows 15.609135 s
```

I just recognized that despite `--tgstype pb` is specified, the names of intermediate files contain `ont`. I guess this is just unawareness of the script.

Thank you very much in advance.
Best regards,
Tilman

**Comment by cchd0001** [comment]
Hi Tilman,

1.  The racon error. First it looks like racon crash , which will always reduce the quality of final result . Then for me this error look like your installed racon doesn't suit your enverionment , howerver this is only an empirical guess .
2. The intermediate files are always named by ont , it is truely misleading . We will update it soon .

Best wishes
Lidong Guo

**Comment by schellt** [comment]
Dear Lidong,
it was really a configuration problem with one of our nodes.
Sorry to bother you.
Best,
Tilman
