### ISSUE TITLE
extend contig ends

### ISSUE THREAD

**Issue by christinawu2008** [BGI-Qingdao/TGS-GapCloser#14]
Hi there,

I'm wondering if TGS-GapCloser could extend the end of the contigs? The 10x assembly apparently miss-assembled telomere sequences which we would like to use long reads to rescue such regions.

Thanks!
Chen

**Comment by adonis316** [comment]
Hi Chen,
TGS-GapCloser is designed for closing the gaps in the assembly, which means both contig ends need to match the long reads. It does not work for a single contig end to extend. 
In your case, I would suggest that cut off the suspicious sequences at the end of the contig first,  align the modified end (>2kbp) to long reads to find the candidate extensions,  and find the best matched long-read segment to finally extend the end to telomere.  You can choose the best segment based on the alignment length and alignment quality. 
Hopefully it could help.

Thanks,
Mengyang

**Comment by christinawu2008** [comment]
Thanks
