### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed

### ISSUE THREAD

**Issue by farhan-phd** [BGI-Qingdao/TGS-GapCloser#15]
Hello author,
I am using TGS_GapCloser on my 1.7G Pacbio genome assembly but there is some unexpected error that happened before the pilon step, according to my experience there is a problem in a sorted file, which can not proceed for further indexing (.bai file) step. I am using samtools (Version: 1.6 (using htslib 1.6)).
Below is an error description:
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: ./TGS_error_correction/test.sort.bam doesn't have sequence for any of 
	at scala.Predef$.require(Predef.scala:277)
	at org.broadinstitute.pilon.BamFile.validateSeqs(BamFile.scala:78)
	at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$1(GenomeFile.scala:87)
	at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$1$adapted(GenomeFile.scala:87)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.broadinstitute.pilon.GenomeFile.processRegions(GenomeFile.scala:87)
	at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:105)
	at org.broadinstitute.pilon.Pilon.main(Pilon.scala)
Command to run TGS-GapCloser is:
path_to_TGS-GapCloser_directory/TGS-GapCloser.sh  --scaff contigs.fasta --reads merg_diff_runs_pacbio.fasta --output test --pilon /softwares/pilon-1.23.jar --ngs  Illumina_R1R2.fastq --samtools path_to_samtools/samtools  --java path_to_java/java -tgstype pb --thread 32 >pipe.log 2>pipe.err &

And here is few lines from header of sorted.bam file
ST-E00104:914:HMGF5CCXY:5:1101:9820:1309	4	*	0	0	*	*	0	0	NCAGTACTGCAGGTAAACTCTTCCCATAGCCCGAA	#AAAFJJJJFJJJJJJJJAFJJJFJJAJJJFJJJ<	rl:i:0
ST-E00104:914:HMGF5CCXY:5:1101:12966:1309	4	*	0	0	*	*	0	0	NAGTCATATTTCCTGCAATCAAGTTTGGTGCGGTTTACCTCGAGTTTGCATCTATTGTCTGCTCTT	#AAAFJFFJFJJJJJJJJFJJJJFJJFFAFJJJJJ--AFA-AFF<J7JFJJJ7J-<A<F-FJJJ-F	rl:i:0
ST-E00104:914:HMGF5CCXY:5:1101:13250:1309	4	*	0	0	*	*	0	0	NAAGAGGCTCCAGGGAGGCTTGCTAGGGCCAAAACACCACGCCCCCCACCCCGTGTTTACTCCCAAGAGGCTCCAGCGAGG	#AAFFJ<AFJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJF<JJJJJAJAFJFJJJJJ-<A<JJFFA-FJF-<7A7FJAJJ	rl:i:0
ST-E00104:914:HMGF5CCXY:5:1101:13656:1309	4	*	0	0	*	*	0	0	NTTAACCTGGAAATAAGGAGAAACTTTCTGACAGTGAGAACAATCAACCAATGGAGCGGCTTTGCCCTTGGAAGTTCTGGGAGCTTCATCACGTGAGACTTTCAAGAGATTGGACTGCCAT	#AAAFJFFJJJJJJJJJJJJFJJJJJJJJJJJJJJJ7FFJAFJJJJJJJJJAAJJ-FJF-7FFAJJJJFJJAJJF7FJAFF<AF-<FAFFAJ-FAJJ<A7FFFFJJJJJFJ-AFJAJJJJA	rl:i:0
ST-E00104:914:HMGF5CCXY:5:1101:14001:1309	4	*	0	0	*	*	0	0	NAAAAATTGAATCCCACTACTGGACAAATTGCATTTATCACTATTGGGTAGAATCTCTGTAATTAAGATGACTGTTTTACCAAAGATGCTTTTTCTGTTCCAGACATTACCAATACTTGCAACTGATAATCCACTTAAACAATGGCAGAG	#A<<FFJ<JJJJJJFJJAJJJJJJJJFJJJ<JFJJ<-AJJ7-FFJF<FFJJJJJJAJJF--FF<JJJJFF7AF

Do you have an idea of what the problem could be?
Thanks,
Maryam

**Comment by adonis316** [comment]
Hi Maryam,
It seems like there is a problem in your sorted.bam.  
1. If you are using Illumina NGS short reads to correct sequencing errors in PacBio reads, then the query is NGS short reads while reference is PacBio long reads. In the sam/bam file, all query sequences are supposed to be uniform 100bp (or 150bp) long, while your sorted.bam file shows various read length. Please check your "--ngs Illumina_R1R2.fastq" file. Also, when you combine read1 and read2 into one file, make sure they do not share the same read ID.
2. The error reported by Pilon means that there are no mapped alignments in the sorted.bam. The first few lines you showed all alignments have no reference name, which proves this point. 

Thanks,
Mengyang

**Comment by farhan-phd** [comment]
Hi Mengyang,

I already tried your recommended strategies, unfortunately, didn't work for me. I did in this way to uniform all reads length of NGS Illumina, but this time it is stuck at minimap2 step with empty ont.fasta files (please see the screenshot). Do you have any advice what is wrong?
![image](https://user-images.githubusercontent.com/61362867/88480684-b24ba000-cf2d-11ea-97bb-fc64fdae5cb5.png)

I even tried to use the PacBio reads instead of NGS reads for corrections using Racoon. But had the same problem. The log file contains the following information
![image](https://user-images.githubusercontent.com/61362867/88480779-56cde200-cf2e-11ea-8d8d-39475a4cfee8.png)


Thanks,
Maryam

**Comment by adonis316** [comment]
Hi Maryam,
It seems like there are no gaps waiting to be closed. The empty *.ont.fasta file means no ont/pacbio long reads that could be mapped to the gaps in the original assembly, and it is irrelevant with polishers, pilon and racon. Also, your minimap2 seems OK. Please check if you have any gaps (Ns) in your input assembly since TGS-GapCloser does not provide additional scaffolding.

Thanks,
Mengyang
