### ISSUE TITLE
how to get scaffolds? 

### ISSUE THREAD

**Issue by bestweicheng** [BGI-Qingdao/TGS-GapCloser#18]
我一定需要使用scaffolds么？利用flye等软件大多数只能获得contigs，输入文件为contigs是否可行？

**Comment by adonis316** [comment]
你好，
TGS-GapCloser是一个补洞软件，是利用三代read去填补scaffold上的N区。如果没有scaffold，只有contig，就没有gap可以填补，TGS-GapCloser无法操作。该软件本质上是一个结合三代与其他测序技术（如PE，10x，stLFR，Hi-C等）的工具。

**Comment by bestweicheng** [comment]
谢谢！
