### ISSUE TITLE
Question about fasta.gz file

### ISSUE THREAD

**Issue by deilepaita** [BGI-Qingdao/TGS-GapCloser#22]
For TGS reads as input you guys indicate ".fasta". I know ".fastq" is not supported as you indicate it clearly in README, but I want to know if ".fasta.gz" is supported as well as ".fasta"

Thanks!

**Comment by adonis316** [comment]
Hi,
The TGS-GapCloser supports gzip compressed file. You can use either FASTA or FASTA.GZ for the TGS long reads as input.

BTW, the FASTA file can be easily extracted from FASTQ by a simple command 
awk '{if(NR%4==1) {printf(">%s\n",substr($0,2));} else if(NR%4==2) print;}'  FASTQ >FASTA

Thanks,
Mengyang

**Comment by deilepaita** [comment]
Hi Mengyang, thanks for the quick answer.

I am running the pipeline using raw Pacbio reads with error correction using racon (long reads only) and fasta.gz files. It starts without problems, but for some reason the pipeline stops during step 2.2. 

In log file: "2.2 , run TGSGapCandidate to choose candidate region seqs." 
In error file the message indicates that the TGSGapCandidate terminated (line 408) and shows the command:

        $Candidate --ont_reads_a $TGS_READS \
        --contig2ont_paf $OUT_PREFIX.sub.paf \
        --candidate_max 10 --candidate_shake_filter --candidate_merge \
        <$TMP_INPUT_SCAFF_INFO >$OUT_PREFIX.ont.fasta 2>$OUT_PREFIX.cand.log || exit 1

Any idea on why this keeps happening? I have run it three times and it keeps stopping at that point. The cand.log stays at LoadPAF.

Thanks,

**Comment by cchd0001** [comment]
Hi .

Could you please provide the cand.log  and some lines of your paf file ? It would be helpful to debug this issue.

Also , is it possible that your paf file was too huge to exceed the memory limitation ? 


Best wishes 
Lidong Guo

**Comment by deilepaita** [comment]
Hi Lidong Guo,

Yes, it was a memory limitation. paf file was huge and never loaded. No need to debug it. 

I divided the genome into parts and make the reference fasta smaller and it is working now! :)

Thanks for developing this tool, and thanks for your quick reply! 

Best wishes,
