### ISSUE TITLE
Arg input_scaff is not assigned !!!

### ISSUE THREAD

**Issue by edeyneka** [BGI-Qingdao/TGS-GapCloser#23]
Hi!
I am running TGS-GapCloser installed with Conda. Here is my input 
```tgsgapcloser --scaff ~/scaffold.fasta --reads ~/reads.fasta --output ~/gapcloser --racon ~/opt/anaconda3/bin/racon```
And here is my error:  

```INFO  :   Run tgsgapcloser from ~/opt/anaconda3/bin ;
          Version : 1.1.1 ;
          Release time : 2019-12-31 .


INFO  :   Parsing args starting ...

INFO  :   Parsing args end .

INFO  :   Checking basic args & env ...

FATAL :   Arg input_scaff is not assigned !!! ! exit ...
 try -h/--help for usage.
```

What might be the problem? Thanks!

**Comment by adonis316** [comment]
Hi,
It looks like that the TGS-GapCloser did not detect the scaffold file. Could you check the input scaffolds again? You could also try the absolute path instead of relative path. 

Thanks,
Mengyang

**Comment by edeyneka** [comment]
Hi Mengyang,

My input scaffold is a fasta file and I provided the absolute path to it (deleted just for the post). This is part of it:
```
>PacBio_ch2
ATGAACATGCTCGCCCCGACGGTCAAGAACGCATTCACCCCGGCGTCGCTGGACCGGCCC
GCTTACCAAAGCGGCTTCGGCAACGAGTTCGCCACCGAAGCCCTGCCCGGCGCGCTGCCG
```

Maybe I should delete ```>PacBio_ch2```?

**Comment by adonis316** [comment]
Hi,
Your scaffold file looks OK, and you do not need to delete the header. 
The error message means some required input argument is missing.
I have tested the command: "tgsgapcloser --scaff scaffold.fasta --reads longreads.fasta --output gapcloser --racon ~/software/anaconda2/bin/racon" and it ran well without any error message.
Could you post the complete log file?

**Comment by edeyneka** [comment]
Hi,
Thank you so much! The log file is here:
```

INFO  :   Run tgsgapcloser from /Users/edeyneka/opt/anaconda3/bin ;
          Version : 1.1.1 ;
          Release time : 2019-12-31 .


INFO  :   Parsing args starting ...

INFO  :   Parsing args end .

INFO  :   Checking basic args & env ...

FATAL :   Arg input_scaff is not assigned !!! ! exit ...
 try -h/--help for usage.
```

So basically it is the same as I posted before... I installed tgsgapcloser with Conda. Maybe this causes an issue?

**Comment by adonis316** [comment]
The conda installation should be OK. I was also using tgsgapcloser installed via conda. 
This is my log file of a successful run:
'''
INFO  :   Run tgsgapcloser from ~/software/anaconda2/bin ;
          Version : 1.1.1 ;
          Release time : 2019-12-31 .


INFO  :   Parsing args starting ...
             --scaff chr19_scaffold.fasta
             --reads chr19.ont.fasta
             --output gapcloser
             --racon  ~/software/anaconda2/bin/racon

INFO  :   Parsing args end .

INFO  :   Checking basic args & env ...
              -   Will do error-correcting by racon.
              -   TGS reads type is ont . MINIMAP2_PARAM is  -x ava-ont   MIN_IDY is 0.3 . MIN_MATCH is 300 .

INFO  :   Checking basic args & env end.

INFO  :   Step 1 , run TGSSeqSplit to split scaffolds into contigs. 

'''

I would suggest to check the command again.  
"tgsgapcloser --scaff scaffold.fasta --reads longreads.fasta --output gapcloser --racon ~/software/anaconda2/bin/racon". The input arguments are split by spaces.

**Comment by edeyneka** [comment]
Can the problem be associated with the fact that I have anaconda3?
Double-checked the command and it seems to be okay

**Comment by cchd0001** [comment]
Hi,
 
Your command looks OK to me but the logs in the log file were not OK. 
 
Based on the logs, those args like ”--scaff” or  “--output”  or “--racon” were not identified by the script. Could it be your input method editor (IME)? The hyphen “--” could be not a standard English input, and thus the script did not detect the args.
 
Best wishes 
Lidong Guo

**Comment by edeyneka** [comment]
Hi,
I rewrote everything again from scratch with the hyphen “--” and I wrote everything directly in the command line so it is not IME issue. So I am really confused what is wrong

Thanks!

**Comment by cchd0001** [comment]
try ```getopt --help```  command . Does this command works ?

**Comment by edeyneka** [comment]
```getopt --help``` gives ```--```
The strange thing is that when I type ```tgsgapcloser -h``` or ```tgsgapcloser --help```, it gives the same error which I reported above.
BTW, I have Mac, maybe this is why it does not work properly (I doubt though)

**Comment by cchd0001** [comment]
![image](https://user-images.githubusercontent.com/8720584/103389631-f715db80-4b4a-11eb-8a0f-b7d10e898a04.png)

This is how I try ```getopt --help```

could you  please try at a linux platform or use a bash like command line tool ?

**Comment by charles5perrier** [comment]
I have the exact same issue on my Mac. I will try on linux.

**Comment by smallfishcui** [comment]
Just to add a piece to this thread. I got the same error,. Strangely, when I type the tgsgapcloser -h, it works, but it doesn't work with  "tgsgapcloser --help". I checked the log file and found that somehow the program doesn't recognize soft linked files or predefined parameters such as $SLURM_CPU_PER_TASK. I replaced these with absolute path and real numbers, then it works.

Cui

**Comment by ad010902** [comment]
> Hi! I am running TGS-GapCloser installed with Conda. Here is my input `tgsgapcloser --scaff ~/scaffold.fasta --reads ~/reads.fasta --output ~/gapcloser --racon ~/opt/anaconda3/bin/racon` And here is my error:
> 
> ```
>           Version : 1.1.1 ;
>           Release time : 2019-12-31 .
> 
> 
> INFO  :   Parsing args starting ...
> 
> INFO  :   Parsing args end .
> 
> INFO  :   Checking basic args & env ...
> 
> FATAL :   Arg input_scaff is not assigned !!! ! exit ...
>  try -h/--help for usage.
> ```
> 
> What might be the problem? Thanks!



> Hi! I am running TGS-GapCloser installed with Conda. Here is my input `tgsgapcloser --scaff ~/scaffold.fasta --reads ~/reads.fasta --output ~/gapcloser --racon ~/opt/anaconda3/bin/racon` And here is my error:
> 
> ```
>           Version : 1.1.1 ;
>           Release time : 2019-12-31 .
> 
> 
> INFO  :   Parsing args starting ...
> 
> INFO  :   Parsing args end .
> 
> INFO  :   Checking basic args & env ...
> 
> FATAL :   Arg input_scaff is not assigned !!! ! exit ...
>  try -h/--help for usage.
> ```
> 
> What might be the problem? Thanks!

Hi,
I had the same error as you, did you fix it and can you help me?
