### ISSUE TITLE
Use of HiFi reads of the PacBio Sequel Systems ?

### ISSUE THREAD

**Issue by agroppi** [BGI-Qingdao/TGS-GapCloser#24]
Is it possible to use HiFi reads produced using the circular consensus sequencing (CCS) mode on one of the PacBio Sequel Systems ?
If yes, what would be the usage arguments for TGS-GapCloser ?
Thanks

**Comment by adonis316** [comment]
Hi,
The base-calling accuracy of HIFI CCS reads is usually >99%. You might use them to directly close gaps without any error corrections by "--tgstype pb --ne". 
However, if you have sufficient NGS or CCS reads, you can still improve the read accuracy by polishing the gap-closing regions. Then the parameters would be the same as PacBio CLR reads "--tgstype pb" + error correction.

Thanks,
Mengyang Xu

**Comment by agroppi** [comment]
Thanks for you answer.
I'll give it a try
Cheers from Bordeaux (France)

**Comment by AgaricX** [comment]
I have a modification of this issue. I have a rather contiguous 3gb assembly made from only CCS reads, so accuracy is excellent, but there are still gaps to close.

I have recently acquired considerable (>100x) Oxford Nanpore reads that have excellent read length, but of course poor accuracy. I do not want to alter the HiFi sequence at all, but would like to link the contigs with the ON reads. Is there a way to ensure the current contigs are not modified at all, but are still able to be pseudo-scaffolded with TGS-GC?

**Comment by adonis316** [comment]
Hi,
TGS-GapCloser will not modify the input contigs while closing gaps with additional long reads. You can use a few of ultra-long Nanopore reads (~10x, considering computational consumption) to close gaps in CCS-based assemblies. 

However, the latest version of TGS-GapCloser does not support further scaffolding. You might try other software tools, such as SSPACE-LongRead, SLR…

**Comment by Hanjiangna** [comment]
what then meaning of "the latest version of TGS-GapCloser does not support further scaffolding" ?
