### ISSUE TITLE
TGSCandidate killed

### ISSUE THREAD

**Issue by NTNguyen13** [BGI-Qingdao/TGS-GapCloser#28]
Hi, I'm running TGS-Gapcloser on a Homo Sapiens de novo assembly. I used ONT reads - around 30X, with error correction by Illumina short reads (around 50X).

I'm running TGS on a machine with 32 cores, 256GB RAM and 500GB SSD, but it got killed at TGSCandidate step, the log is as follow

```
INFO  :   Parsing args end .

INFO  :   Checking basic args & env ...
              -   Will do error-correcting by pilon with ngs-reads.
              -   TGS reads type is ont . MINIMAP2_PARAM is  -x ava-ont   MIN_IDY is 0.3 . MIN_MATCH is 300 .

INFO  :   Checking basic args & env end.

INFO  :   Step 1 , run TGSSeqSplit to split scaffolds into contigs.

INFO  :   Step 1 , done .

INFO  :   Step 2 , run TGSCandidate ...
              -   2.1 , run minmap2 to map contig into tgs-reads.
              -   2.2 , run TGSGapCandidate to choose candidate region seqs.
/home/ubuntu/anaconda3/envs/tgs/bin/tgsgapcloser: line 374: 20923 Killed                  $Candidate --ont_reads_a $TGS_READS --contig2ont_paf $OUT_PREFIX.sub.paf --candidate_max 10 --candidate_shake_filter --candidate_merge < $TMP_INPUT_SCAFF_INFO > $OUT_PREFIX.ont.fasta 2> $OUT_PREFIX.cand.log
```

Could you please clarify the reason why it got killed? And how is the specification needed for running the dataset? 
Thank you very much

**Comment by cchd0001** [comment]
Hi ，

May be the paf file is too huge to load into your memory, please check this.

Best wishes
Lidong Guo

**Comment by NTNguyen13** [comment]
Hi, I forgot to mention the paf file. Its size is 136G, I think it can still fit the 256GB memory, am I right?

**Comment by adonis316** [comment]
Seems like your TGS-GapCloser was terminated by the system or administrator. Please check if there is any other process running on the same machine at the same time.  

By the way, if the memory is a problem, then you can try to split the reference genome (scaffolds) into several parts, and run TGS-GapCloser with all TGS long reads separately. In the end, merge all results into one. It could dramatically reduce the memory usage.

Thanks,
Mengyang

**Comment by NTNguyen13** [comment]
I solely used the machine for this task, so I think no other task interrupted it. Splitting the reference genome may lead to the case that 1 read fills multiple gaps, so I want to try if it's possible to run the whole genome at once.

Could you please have some suggestions for the memory size?

**Comment by adonis316** [comment]
You could also try to sample the TGS long reads. Then iteratively use a portion to close the gaps.

**Comment by NTNguyen13** [comment]
Thank you, I will subsample the TGS by 33% and try again

**Comment by NTNguyen13** [comment]
Hi, I have subsampled the TGS data about 33% (now it's 33.6GB) then run the script again. It still got killed:
```
(tgs) ubuntu@ip-172-31-30-210:~$ tgsgapcloser \
>     --scaff $scaffold \
>     --reads $ont_fasta \
>     --output $scaffold_dir/TGS \
>     --tgstype ont \
>     --pilon  ~/pilon-1.23.jar  \
>     --ngs    $interleave_ilmn  \
>     --samtools /usr/bin/samtools  \
>     --java    /usr/bin/java \
>     --thread 32
INFO  :   Run tgsgapcloser from /home/ubuntu/anaconda3/envs/tgs/bin ;
          Version : 1.1.1 ;
          Release time : 2019-12-31 .


INFO  :   Parsing args starting ...
             --scaff s3-drive/ragtag.scaffolds.primary.noY_hifi.fasta
             --reads s3-drive/NA12878-minion-ul_GRCh38_10X.trimmed_empty.fasta
             --output Scaffolded_primary_noY.RagTag_correctfirst_byread.tgsgapcloser_ont10X_correction/TGS
             --tgstype ont
             --pilon  /home/ubuntu/pilon-1.23.jar
             --ngs    s3-drive/BH814YADXX_50X_interleaved.fastq.gz
             --samtools  /usr/bin/samtools
             --java  /usr/bin/java
             --thread 32

INFO  :   Parsing args end .

INFO  :   Checking basic args & env ...
              -   Will do error-correcting by pilon with ngs-reads. 
              -   TGS reads type is ont . MINIMAP2_PARAM is  -x ava-ont   MIN_IDY is 0.3 . MIN_MATCH is 300 .

INFO  :   Checking basic args & env end.

INFO  :   Step 1 , run TGSSeqSplit to split scaffolds into contigs. 

INFO  :   Step 1 , done .

INFO  :   Step 2 , run TGSCandidate ... 
              -   2.1 , run minmap2 to map contig into tgs-reads.
              -   2.2 , run TGSGapCandidate to choose candidate region seqs.
/home/ubuntu/anaconda3/envs/tgs/bin/tgsgapcloser: line 374: 15885 Aborted                 (core dumped) $Candidate --ont_reads_a $TGS_READS --contig2ont_paf $OUT_PREFIX.sub.paf --candidate_max 10 --candidate_shake_filter --candidate_merge < $TMP_INPUT_SCAFF_INFO > $OUT_PREFIX.ont.fasta 2> $OUT_PREFIX.cand.log
```

The last line in TGS.cand.log file is:

```
TGSGapCandidate	INFO	UTC	2021/3/26	7:45:18	:	LoadPAF finish. used wall clock : 2851 seconds, cpu time : 2850.497314 seconds
TGSGapCandidate	INFO	UTC	2021/3/26	7:45:18	:	LoadScaffInfo start now ... 
TGSGapCandidate	INFO	UTC	2021/3/26	7:45:54	:	LoadScaffInfo finish. used wall clock : 36 seconds, cpu time : 36.150925 seconds
TGSGapCandidate	INFO	UTC	2021/3/26	7:45:54	:	ParseAllGap start now ... 
tgsgapcandidate: tgsgapcandidate.cpp:221: void AppConfig::LogAllChoose(const ONT2GapInfos&, const BGIQD::stLFR::ContigDetail&): Assertion `0' failed.
```

**Comment by cchd0001** [comment]
Hi,

I have modified the code. Would you please download and test it again?

Best wishes
Lidong Guo

**Comment by NTNguyen13** [comment]
Hi, I think that the TGSCandidate runs without problem now. However, the next step consumes quite a bit of the storage, so it stopped at writing output. Could I resume the run after increasing the storage? It stopped at:

```
INFO  :   Step 3.B , error correction by pilon ...  
              -   3.B.1 ,  pilon each chunk ...  
              -      -   iteration 0 start ... 
              -      -   iteration 0 chunk 0 -  minimap2 indexing ... 
              -      -   iteration 0 chunk 0 -  minimap2 mapping ngs into tgs ..
```

**Comment by cchd0001** [comment]
Hi,

The latest TGS-GapCloser pipeline in Github can re-run based on the tag files but the tgs-gapcloser pipeline from conda can't. 

To re-run from your current state, please 
1. use the Github version pipeline.
2. create the tag files by 

```
touch done_step1_tag
touch done_step2.1_tag
touch done_step2.2_tag
touch done_step2.3_tag
```

Best wishes
Lidong Guo

**Comment by NTNguyen13** [comment]
Thank you very much!
