### ISSUE TITLE
-g_check flag

### ISSUE THREAD

**Issue by KyleEwart** [BGI-Qingdao/TGS-GapCloser#35]
Hi,
Thanks for develpoing this program. I have used the program to improve my assembly BUSCO score with very low-coverage HiFi data.
Can you please elaborate on what the '--g_check' flag does. Apologies if this is already explained in the documentation - I can only see a brief explanation of this flag.
Thanks

**Comment by cchd0001** [comment]
Hi, 

Set the ```--g_check``` flag will open the _gap size checking function_  for length>100bp gaps : 

reject the gap-filling action if the length of the sequence to fill this gap is either smaller than 50% of the original gap size or greater than 100% of the original gap size.

Best wishes
Lidong Guo
