### ISSUE TITLE
--minmap_arg arg not present in conda install

### ISSUE THREAD

**Issue by charlesfeigin** [BGI-Qingdao/TGS-GapCloser#36]
Hi!

Excited to use your program. I installed the conda version (1.1.1) and noticed that the --minmap_arg is no longer present (and shows as unrecognized options in the err file). I am hoping to gap-fill an assembly using PacBio HiFi reads and was planning to use --minmap_arg '-x asm20' as suggested in the github page example. Do you know what an equivalent set of options would be in v1.1.1? Thanks!

Best,
Charles

**Comment by cchd0001** [comment]
Hi ,

please change the line 313 in tgsgapcloser, from ```MINIMAP2_PARAM=" -x ava-pb "``` to ```MINIMAP2_PARAM="-x asm20 " ```, and set  ``` --tgstype pd ```
