### ISSUE TITLE
Conda invoke

### ISSUE THREAD

**Issue by ardy20** [BGI-Qingdao/TGS-GapCloser#37]
Hi 

I am trying to use your tool but I do not know how to run it through conda. I use the following but I get error command not found:

TGS-GapCloser.sh --thread 24 --scaff MJ_hifiasm_assembly.fa --reads mj.combined.fasta --tgstype pb --output out_hifiasm-gapclose --ne

**Comment by adonis316** [comment]
Hi,
The command should be "tgsgapcloser". For example, in your case:
"tgsgapcloser --thread 24 --scaff MJ_hifiasm_assembly.fa --reads mj.combined.fasta --tgstype pb --output out_hifiasm-gapclose --ne".

Note that only scaffold sequences with unknown bases "N" can be filled.

Thanks,
Mengyang

**Comment by ardy20** [comment]
Hi Thanks
What is the other option to fill gaps? I do not have "N" in my scaffolds but would like to reduce the number of contigs. 
Regards
Ardy

**Comment by adonis316** [comment]
TGS-Gapcloser requires contig relations provided by scaffolding to connect contigs and reduce the contig number. You might need a scaffolder to build scaffolds first, and then close gaps (replace N's) between contigs within the same scaffold by TGS-Gapcloser.
