### ISSUE TITLE
big RAM required

### ISSUE THREAD

**Issue by ardy20** [BGI-Qingdao/TGS-GapCloser#38]
Hi Author

I tried this tool on a 500 Mb genome and used 300 Gb of RAM. The tool failed because needed more RAM. Is there any parameter that can limit the RAM requirement (in --ne mode) (no polish mode).

Regards
Ardy

**Comment by adonis316** [comment]
The memory usage is usually not large for the ne mode, in which the alignment consumes the most memory by minimap2. 300Gb should be enough for a 500Mb genome. Could you provide more details in the log files?

Mengyang
