### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by markcharder** [BGI-Qingdao/TGS-GapCloser#39]
I've tried running TGS GapCloser as both a conda installation and a source installation and both times I get the following error:

/data/software/miniconda2/envs/tgsgapcloser/bin/tgsgapcloser: line 374: 2187092 Aborted                 (core dumped) $Candidate --ont_reads_a $TGS_READS --contig2ont_paf $OUT_PREFIX.sub.paf --candidate_max 10 --candidate_shake_filter --candidate_merge < $TMP_INPUT_SCAFF_INFO > $OUT_PREFIX.ont.fasta 2> $OUT_PREFIX.cand.log

Ubuntu 20.04.2 LTS

**Comment by adonis316** [comment]
Hi,
Can you please provide us a few input sequences and all log files? Note that TGS-GapCloser will work only if the input scaffolds have unknown “N” sequences.

Thanks,
Mengyang

**Comment by markcharder** [comment]
I have found that the problem was that TGS-GapCloser requires reads in fasta format but I had reads in fastq format. Sorry for the post. Closing the issue.
