### ISSUE TITLE
TGS-GapCloser支持Pacbio HiFi数据吗？

### ISSUE THREAD

**Issue by Deng-Yuan** [BGI-Qingdao/TGS-GapCloser#40]
基于Pacbio HiFi数据组装的基因组可以用这个软件在初步组装的基础上利用HIFI数据进行Gap填充吗？

**Comment by adonis316** [comment]
你好，
可以用HIFI reads，需要选择以下参数：

**Comment by adonis316** [comment]
你好，

**Comment by adonis316** [comment]
你好，
可以用HIFI reads进行补洞，需要选择以下参数：
1. error correction: 可以选择不对hifi reads进行纠错，--ne;
2. mapping: 如果是GitHub安装，可以选择参数  --minmap_arg '-x asm20'；如果是conda安装，需人工修改tgsgapcloser的第 313行, from MINIMAP2_PARAM=" -x ava-pb " to MINIMAP2_PARAM="-x asm20 "
3. candidate selection:  需设置 --tgstype pb
