### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by leone93** [BGI-Qingdao/TGS-GapCloser#42]
Hi all, 
I'm trying to use the tools but it seems there is some problem with the use of the memory that  I don't understand.
First time I tried the tool it fails for exceeding memory request. Second time I saw this error in the pipe.err file:

> bin/tgsgapcloser: line 374: 256842 Segmentation fault      (core dumped) $MiniMap2 $MINIMAP2_PARAM -t $THREAD $TGS_READS $TMP_INPUT_SCAFTIG > $OUT_PREFIX.sub.paf 2> $OUT_PREFIX.minimap2.01.log

Do someone has the same error?

**Comment by cchd0001** [comment]
Hi,

It looks like that your data trigger some minimap2's bug.
Could you please test this minimap2 command (``` path-latest/minimap2  -x ava-pb -t 40 reads.fa  xxx.contig >out.paf 2>out.log``` ) with your data and the latest version of minimap2  ?　

If the latest minimap2 works, please change the ```MiniMap2=$HOOM_DIR"/minimap2/minimap2"``` to your minimap2 and try again.

Best w

**Comment by leone93** [comment]
minimap2 is already at the latest version

**Comment by cchd0001** [comment]
It looks like a minimap2 incompatible issue with PB-HiFi reads. Could you please provide the entire log of minimap2?  
You can reduce the memory cost by add ```-K 80M```  to minimap2 command as suggested by Heng Li. Please find more details in [issue570 ](https://github.com/lh3/minimap2/issues/570) and [issue375 ](https://github.com/lh3/minimap2/issues/376) of minimap2.

**Comment by leone93** [comment]
`[M::mm_idx_gen::82.863*1.86] collected minimizers
[M::mm_idx_gen::92.276*3.14] sorted minimizers
[M::main::92.276*3.14] loaded/built the index for 234199 target sequence(s)
[M::mm_mapopt_update::94.397*3.09] mid_occ = 2352
[M::mm_idx_stat] kmer size: 19; skip: 5; is_hpc: 1; #seq: 234199
[M::mm_idx_stat::95.134*3.08] distinct minimizers: 79140528 (8.53% are singletons); average occurrences: 12.125; average spacing: 4.169; total length: 4000702366
[morecore] insufficient memory`

This is the out.log of minimap2

**Comment by cchd0001** [comment]
Yes, this is a minimap2 issue .
 
Please also check [this minimap2 issue link](https://github.com/lh3/minimap2/issues/503). 

Briefly,  please try to reduce ```-t thread_number``` and the ```-K  query_base```  until it fits your RAM size.
