### ISSUE TITLE
Is 10x-linked reads availble for TGS-GapCloser?

### ISSUE THREAD

**Issue by ClarenceHsiang** [BGI-Qingdao/TGS-GapCloser#45]
Dear TGS-GapCloser developers:

Good evening.

I would like to use 10x-linked reads for GapClosing, is there any setting that should be modified?  

Thank you very much.

**Comment by adonis316** [comment]
Thank you for choosing TGS-GapCloser. However, this software tool is designed for third-generation long reads (Oxford nanopore, PacBio) to close gaps. As long fragments are sequenced highly sparsely (~20% coverage) for 10X-linked reads, they cannot provide ATCG sequences to fill gaps. 

I would suggest to use NGS short-read gap closer, such as SOAPdenovo GapCloser v1.12 (https://sourceforge.net/projects/soapdenovo2/files/GapCloser/bin/r6/GapCloser-bin-v1.12-r6.tgz/download).

Thanks,
Mengyang
