### ISSUE TITLE
Combine two assemblies

### ISSUE THREAD

**Issue by oushujun** [BGI-Qingdao/TGS-GapCloser#48]
Hello,

Thank you for developing this great tool. I understand this is not the primary function of TGS-GapCloser, but I want to combine two assemblies. Below are their basic stats:

```
Assembly 1
Number of contigs        711
Total size of contigs  792060035
Longest contig   24010295
Mean contig size    1114008
N50 contig length    6877865
 
Assembly 2
Number of contigs        992
Total size of contigs  847172677
Longest contig   52478269
Mean contig size     854005
N50 contig length   20092841
```

I want to use assembly 1 to patch assembly 2. Assembly 1 is ONT based. This is the command I used:
`tgsgapcloser --scaff assembly2.fasta --reads assembly1.fasta --output assembly2.fasta.tgsgapcloser --tgstype ont --thread 40 --ne`

The run finished without errors, however, the resulting file `assembly2.fasta.tgsgapcloser.scaff_seqs` has no gap being closed. Is there any parameter tuning I can do? Thank you.

Best,
Shujun

**Comment by adonis316** [comment]
Hi Shujun,
It is possible to use one assembly to close gaps in the other assembly. But there must be real gaps (consecutive N’s) in that target assembly.

Usually, ONT or Pacbio assemblers only generate contigs without any N sequences, which is impossible to close gaps by replacing N’s. If you build scaffolds using other sequencing information, i.e., stLFR, 10XG, Bionano, and Hi-C, then you can use contigs in another assembly to close their gaps.

Thanks,
Mengyang

**Comment by oushujun** [comment]
Hi Mengyang,

If ONT can bridge two separate contigs, is it possible for TGS-GapCloser to make the connection and combine the two contigs with ONT information together?

Shujun

**Comment by adonis316** [comment]
Hi Shujun,
It is a great point. And we are planning to add this function module to our next version. But currently what you need is a TGS scaffolder, i.e., LRScaf, Gapless. After the scaffolding connections are built, you might run TGS-GapCloser to close the new gaps then. 

Thanks,
Mengyang
