### ISSUE TITLE
why use the reads as target

### ISSUE THREAD

**Issue by tinyfallen** [BGI-Qingdao/TGS-GapCloser#50]
Hi dear developer,

Thanks for your great works! I have tried to close a few gaps in my plant assembly, however the pipeline always terminated at step 2.1 as the minimap2 produced an enormous core.***(seem to be a random number suffix) file and threw out a core dumped as [issue42](https://github.com/BGI-Qingdao/TGS-GapCloser/issues/42) described. As the server loading is full now, I could only delay the test of the method mentioned above.
Looking into the scripts I am confused about that in the mapping step why use the reads as target ? The contigs always have much longer length and fewer number than the reads used for assembly in order of magnitudes, which may caused the issue.

Looking forward to your reply! 
BEST~

**Comment by cchd0001** [comment]
Hi, 

Why use reads as target :

1. The TGS-GapCloser was first designed to fill gaps in scaffolds that assembled by NGS reads. In that scenario, contigs are not always longer that TGS reads.
2. Using reads as target will increase the number of final filled gaps.

Why program crash:

For huge genome like some plant  with high coverage reads, this strategy will let minimap2 consume a huge memory cost and may case crash if exceed the maximum available memory size.  

In some machine, crashed program saves the screenshot into core file like you described. Please delete it. 

Please check issue42 to find the solution.

**Comment by tinyfallen** [comment]
Hi，

Thanks for your explanation! I will try to split reads and assembly to do the trick.

Best!

**Comment by adonis316** [comment]
Hi,
Thanks again for your suggestion! We do consider updating an option that allows users to choose scaffolds as the target to save memory. 

Thanks,
Mengyang

**Comment by tinyfallen** [comment]
Hi dear developer,

I am trying to map all the corrected reads to the assembly first and then extract reads which map to specific pseudochromosome to feed gapcloser one-by-one as a reads splitting method. Do you think it is workable？

Thanks~

**Comment by adonis316** [comment]
Seems great! But please keep mapping reads as many as possible since multi-alignments may decrease the number of filled gaps. Specifically, you can output N>=5 best alignments and use some reads (repetitive region) more than once.

Mengyang

**Comment by tinyfallen** [comment]
> 

Ok, I am running to test the effect! Thank you~

**Comment by tinyfallen** [comment]
Hi dear,

Finally I extracted the ont reads mapped to the region including 100kb up and down the gaps and the gaps number reduced from 13 to 5. I think it is the limitation of the data. 

By the way, I met another issue during closing gaps in another genome and I will talk about it in a new chart.
