### ISSUE TITLE
chromosome much lengthened after filling gaps

### ISSUE THREAD

**Issue by tinyfallen** [BGI-Qingdao/TGS-GapCloser#51]
Hi dear developer,

Using an ONT-Ultralong assembly as the reads to fill gaps in a hifi asm seems effective. However a strange issue occurred in one of 12 chromosomes. After gap filling, it lengthened 40Mb without gaps though it was 48Mb before. 
![chr11](https://user-images.githubusercontent.com/37066354/185532879-b6db1915-2148-4dc4-b436-c94d54b215f6.png)
Could you please give me some suggestions, thanks!

**Comment by adonis316** [comment]
Hi,
TGS-GapCloser closes gaps based on the alignments of the assembly against long reads, resulting in two cases: filled gaps with extra ATCG sequences or merged neighboring contigs. It seems like there exist overlaps between two neighboring contigs in your assembly. This is why the total length is reduced. Please check if there were several N’s in the original sequence. It could generate N’s by long-read assemblers such as Hifiasm.

Thanks,
Mengyang

**Comment by Wyinghao** [comment]
> Hi dear developer,
> 
> Using an ONT-Ultralong assembly as the reads to fill gaps in a hifi asm seems effective. However a strange issue occurred in one of 12 chromosomes. After gap filling, it lengthened 40Mb without gaps though it was 48Mb before. ![chr11](https://user-images.githubusercontent.com/37066354/185532879-b6db1915-2148-4dc4-b436-c94d54b215f6.png) Could you please give me some suggestions, thanks!

HI,I encountered a situation similar to yours, can you tell me how you solved it?

**Comment by Wyinghao** [comment]
> Hi dear developer,
> 
> Using an ONT-Ultralong assembly as the reads to fill gaps in a hifi asm seems effective. However a strange issue occurred in one of 12 chromosomes. After gap filling, it lengthened 40Mb without gaps though it was 48Mb before. ![chr11](https://user-images.githubusercontent.com/37066354/185532879-b6db1915-2148-4dc4-b436-c94d54b215f6.png) Could you please give me some suggestions, thanks!

Hi,I encountered a situation similar to yours, can you tell me how you solved it?Thanks!

**Comment by tinyfallen** [comment]
> > Hi dear developer,
> > Using an ONT-Ultralong assembly as the reads to fill gaps in a hifi asm seems effective. However a strange issue occurred in one of 12 chromosomes. After gap filling, it lengthened 40Mb without gaps though it was 48Mb before. ![chr11](https://user-images.githubusercontent.com/37066354/185532879-b6db1915-2148-4dc4-b436-c94d54b215f6.png) Could you please give me some suggestions, thanks!
> 
> Hi,I encountered a situation similar to yours, can you tell me how you solved it?Thanks!

You could try to align the flanking 5kb sequence in both ends of your gaps to your long reads or contigs by minimap2, if both ends map to one read or contig, it is what you want. Otherwise, I also have no idea.
