### ISSUE TITLE
Passing parameters to RACON?

### ISSUE THREAD

**Issue by cement-head** [BGI-Qingdao/TGS-GapCloser#52]
Hello,

  I've compiled RACON for CUDA usage, is there a means to pass parameters (options) to RACON in TGS-GapCloser?

  If so,how could I accomplish this?

**Comment by cchd0001** [comment]
Hi,

Thank you for your interest in this project.

There is no special parameter for RACON in TGS-GapCloser.  You can directly put your options in TGS-GapCloser.sh line479.  

Best wishes
Lidong Guo
