### ISSUE TITLE
Does TGS-GapCloser connect contigs with overlaps to generate a longer scaffold?

### ISSUE THREAD

**Issue by shaobinzhong** [BGI-Qingdao/TGS-GapCloser#53]
Hello, 

Thanks for developing this program for filling N-gaps in the genome assembly. We have a genome assembly consisting of 157 contigs with many N-gaps. This assembly was generated by short reads and pair-mates. Now we have long reads from Ont and PacBio. We used the long reads to fill the N-gaps but the number of the contigs remained the same (157 contigs) after the gap filling process. Does TGS-GapCloser connect contigs with overlaps to generate a longer scaffold? Thanks.

**Comment by cchd0001** [comment]
Hello,

Thank you for your interest in this software. TGSGapCloser does not re-scaffold the input scaffolds. However, it does fill N-gaps to connect neighboring contigs within the same scaffold using sequences of ONT or PacBio reads.

In your scenario, it seems there were no gaps filled by this software for some reason. Could you please provide the log file for further analysis?

Best wishes
Lidong Guo

**Comment by shaobinzhong** [comment]
Hi Lidong,

Thanks for your reply. After filling the N-gaps with either ccs reads or ONT reads for the assembly, the number of gaps were much less:

1. stats for the original assembly that has been published:
sum = 34417436, n = 157, ave = 219219.34, largest = 3642493
N50 = 1789485, n = 7
N60 = 1726533, n = 9
N70 = 1396008, n = 12
N80 = 1310208, n = 14
N90 = 1003746, n = 17
N100 = 2011, n = 157
N_count = 1196549
Gaps = 358

2. stats for gaps-filled assembly with ccs reads:
sum = 34428672, n = 157, ave = 219290.90, largest = 3638366
N50 = 1790623, n = 7
N60 = 1733892, n = 9
N70 = 1390204, n = 12
N80 = 1318955, n = 14
N90 = 1003634, n = 17
N100 = 2011, n = 157
N_count = 26828
Gaps = 20

3. stats for gaps-filled assembly with ONT reads:
sum = 34420605, n = 157, ave = 219239.52, largest = 3638173
N50 = 1790705, n = 7
N60 = 1734939, n = 9
N70 = 1390219, n = 12
N80 = 1318824, n = 14
N90 = 1003625, n = 17
N100 = 2011, n = 157
N_count = 25254
Gaps = 19

However, to my surprise, not all Ns and gaps were filled with either of the long reads. We have a very high genome coverage for the sequence data from ccs reads and ONT reads (600x and 380x, respectively) for the same genome. When I did de novo assembly with the ccs reads or ONT reads, the assemblies were much better than the original one and the gaps-filled ones in terms of continuity and there are no N-gaps. The reason I would like to fill the N-gaps in the original published assembly is for comparisons.

Best regards.

Shaobin

**Comment by cchd0001** [comment]
Hi Shaobin,

Thanks for sharing the above information. It seems reasonable that not all gaps were filled.
 
Assembly errors of input scaffolds will induce unfilled gaps. To guarantee the accuracy of filled sequences, we set several thresholds to filter suspicious alignments which may cause failure to fill the gaps. 

With such a high sequencing depth of CCS reads, a direct assembly of CCS reads can generate high-quality contigs.  If you scaffold the TGS-assembled contigs by Hi-C reads, we also recommend you to fill the gaps with this software.

Best wishes
Lidong Guo
