### ISSUE TITLE
TGS-gapcloser: Aaborted (core dumped) 

### ISSUE THREAD

**Issue by liuxin-21d** [BGI-Qingdao/TGS-GapCloser#54]
Hi Dear Developer,
I first used ont long reads to fill gaps. In most cases, it works well, but sometimes, it was aborted by accident.  
When i used hifi reads to fill gaps, it always was killed by system. ERRORS like: 
![截屏2022-09-28 22 10 03](https://user-images.githubusercontent.com/111989397/192801391-ba44bbd2-88b5-4986-b461-5a13116afbc6.png)

![截屏2022-09-28 22 13 12](https://user-images.githubusercontent.com/111989397/192802184-59ebfc9e-2d96-42f9-8108-b607b1cca08f.png)

always being aborted in filling gaps:
![截屏2022-09-28 22 14 32](https://user-images.githubusercontent.com/111989397/192802565-392d59a5-9228-477e-98e6-67d562638e1b.png)

what should i do to avoid being aborted (core dumped), 
Any help would be appreciated!

Xin Liu

**Comment by cchd0001** [comment]
Hi Xin Liu,

Thanks for your interest in this project. Could you please provide more details of the file hifill.fill.log?

Normally, the "std::bad_alloc" error means that the process requires more memory than you provided. Please check #49 and #42 for more details.

Best wishes
Lidong Guo

**Comment by liuxin-21d** [comment]
Hi Lidong, 

Thank you for your reply. Here are the hifill.fill.log.
![截屏2022-09-29 09 28 13](https://user-images.githubusercontent.com/111989397/192917862-3677ca8b-b8df-4df9-b475-df460f06897e.png)

Xin Liu

**Comment by cchd0001** [comment]
Please check https://github.com/BGI-Qingdao/TGS-GapCloser/issues/49 and https://github.com/BGI-Qingdao/TGS-GapCloser/issues/42 for more details
