### ISSUE TITLE
step4.2 finish ,but only test.gapclose.fa.updated_scaff_infos file

### ISSUE THREAD

**Issue by feiyu007** [BGI-Qingdao/TGS-GapCloser#56]
commond:tgsgapcloser --prefix test.gapclose.fa --contig2ont_paf test.gapclose.fa.fill.paf --ont_reads_a cns_final.fasta.gz --min_match 300 --min_idy 0.300000
when I finish the commond, only output a test.gapclose.fa.updated_scaff_infos, without test.gapclose.fa.gap_fill_detail and test.gapclose.fa.scaff_seqs files.
log file cannot find any wrong infomation.

**Comment by cchd0001** [comment]
Yes and please run tgsseqgen to generate test.gapclose.fa.gap_fill_detail and test.gapclose.fa.scaff_seqs files

**Comment by feiyu007** [comment]
Thank you!
