### ISSUE TITLE
read-correction crashes

### ISSUE THREAD

**Issue by dominik-handler** [BGI-Qingdao/TGS-GapCloser#6]
Hi, I am trying to run TGS-GapCloser with RACON read correction. I get the follwoing error message:
`/install/TGS-GapCloser/TGS-GapCloser.sh: line 366: 26837 Aborted                 $Candidate --ont_reads_a $TGS_READS --contig2ont_paf $OUT_PREFIX.sub.paf --candidate_max 10 --candidate_shake_filter --candidate_merge < $TMP_INPUT_SCAFF_INFO > $OUT_PREFIX.ont.fasta 2> $OUT_PREFIX.cand.log`

I am certain that it is not a memory problem as plenty should be available. 
Do you have any idea what can be wrong here? If required I can give you access to the folder containing the data. 

Thank you,
Dominik

**Comment by cchd0001** [comment]
Hi  Dominik,
     Please check your $TGS_READS , FASTQ format is not supported and always cause crash.
     If  TGS_READS is in FSATA format , please provide me a small piece of data that can reproduce this crash so that I can debug it , thanks 

Best wishes 
Lidong

**Comment by dominik-handler** [comment]
Ah, thank you for your reply. My reads are indeed FASTQ. Will try again after converting them to FASTA.

All the best,
Dominik
