### ISSUE TITLE
tgsgapcloser: line 645: 81794 Aborted (core dumped)

### ISSUE THREAD

**Issue by Ssmile333** [BGI-Qingdao/TGS-GapCloser#64]
tgsgapcloser: line 645: 81794 Aborted                 (core dumped) $GapCloser --ont_reads_a $FINAL_READS --contig2ont_paf $OUT_PREFIX.fill.paf --min_match=$MIN_MATCH --min_idy=$MIN_IDY --prefix $OUT_PREFIX > $OUT_PREFIX.fill.log 2>&1

Running tgsgapcloser gives the above error, but my paf file is only 3.3G and the memory seems to be sufficient, is there any way to fix it?Thanks

free -h
              total        used        free      shared  buff/cache   available
Mem:           3.0T         85G        172G        140M        2.7T        2.9T
Swap:           15G        417M         15G

**Comment by cchd0001** [comment]
Hi,

Yes. the GapCloser step normally doesn't need a huge memory.

Could you please provide the content of the xxx.fill.log file?

Best wishes
Lidong Guo

**Comment by Ssmile333** [comment]
Thanks.
The follow content is the xxx.fill.log
tgsgapcloser --prefix Chr1_01 --contig2ont_paf Chr1_01.fill.paf --ont_reads_a test.correctedReads.fasta.gz --min_match 300 --min_idy 0.300000
TGSGapCloser	INFO	CST	2023/6/24	23:51:21	:	TGSGapCloser start now ... 
TGSGapCloser	INFO	CST	2023/6/24	23:51:21	:	LoadONTReads start now ... 
TGSGapCloser	INFO	CST	2023/6/24	23:53:9	:	LoadONTReads finish. used wall clock : 108 seconds, cpu time : 107.945145 seconds
TGSGapCloser	INFO	CST	2023/6/24	23:53:9	:	LoadPAF start now ... 
TGSGapCloser	INFO	CST	2023/6/24	23:55:40	:	>the read2contig freq is 
1	64584
2	106835
3	80429
4	30148
5	6157
6	860
7	93
8	2

TGSGapCloser	INFO	CST	2023/6/24	23:55:40	:	>the contig2read_num_freq freq is 
423	1
4322	1
4600	1
5391	1
8429	1
17218	1
24517	1
136462	1
220125	1
255258	1

TGSGapCloser	INFO	CST	2023/6/24	23:55:40	:	>the contig2a_read_freq freq is 
1	201289
2	124551
3	87303
4	62601
5	46350
6	35754
7	26883
8	20534
9	15672
10	11884
11	9324
12	7200
13	5723
14	4452
15	3450
16	2662
17	2087
18	1735
19	1303
20	1088
21	890
22	718
23	529
24	451
25	368
26	294
27	253
28	229
29	178
30	143
31	128
32	100
33	95
34	72
35	56
36	42
37	58
38	45
39	39
40	34
41	21
42	18
43	11
44	24
45	12
46	9
47	13
48	10
49	9
50	11
51	3
52	2
53	4
54	2
55	4
56	3
57	1
58	3
59	1
60	1
61	3
62	1
63	2
64	1
67	2
71	1
72	2
73	2
93	1
99	1

TGSGapCloser	INFO	CST	2023/6/24	23:55:40	:	LoadPAF finish. used wall clock : 151 seconds, cpu time : 151.139252 seconds
TGSGapCloser	INFO	CST	2023/6/24	23:55:40	:	LoadScaffInfo start now ... 
TGSGapCloser	INFO	CST	2023/6/24	23:55:41	:	LoadScaffInfo finish. used wall clock : 1 seconds, cpu time : 0.301835 seconds
TGSGapCloser	INFO	CST	2023/6/24	23:55:41	:	ParseAllGap start now ... 
overlap check c1=1	and Try c2=2	-35219
overlap check c1=1	and Try c2=2	-35158
overlap check c1=1	and Try c2=2	-35226
overlap check c1=1	and Try c2=2	-43100
overlap check c1=1	and Try c2=2	-35077
overlap check c1=1	and Try c2=2	-35246
overlap check c1=1	and Try c2=2	-35101
overlap check c1=2	and Try c2=3	-3046
overlap check c1=2	and Try c2=3	-7904
overlap check c1=4	and Try c2=5	-79
79	500	64	0.810127	1
 accept this overlap 
*** stack smashing detected ***: <unknown> terminated


 Best wishes

**Comment by cchd0001** [comment]
Hi

This is the first time I've seen this bug. It seems unlikely to find problems by simply reading the source code. 

Could you please provide a small piece of data that can trigger this issue for me to debug?

Best wishes
Lidong Guo

**Comment by Ssmile333** [comment]
Hello!
&nbsp;I can&nbsp;provide a small piece of data, but how do I send it to you when the ont data is still 6 gigabytes compressed? Is it possible to request an alternative contact
Best wishes


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BGI-Qingdao/TGS-GapCloser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月25日(星期天) 下午2:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BGI-Qingdao/TGS-GapCloser] tgsgapcloser: line 645: 81794 Aborted (core dumped) (Issue #64)





 
Hi
 
This is the first time I've seen this bug. It seems unlikely to find problems by simply reading the source code.
 
Could you please provide a small piece of data that can trigger this issue for me to debug?
 
Best wishes
 Lidong Guo

**Comment by cchd0001** [comment]
Please upload the data to some cloud server and email me the download link .
My email : guolidong@genomics.cn
