### ISSUE TITLE
Can I use contigs files to fill in the gaps?

### ISSUE THREAD

**Issue by yangchouxianyu** [BGI-Qingdao/TGS-GapCloser#67]
Thanks for developing software.
Can I use contigs files to fill in the gaps? To be specific ,--reads are contigs files such as output file of hifiasm. Can it be used like this?

**Comment by adonis316** [comment]
Sorry for the late response. Absolutely Sure. You can use contigs as error-corrected long reads to fill the gaps in the genome. There is no need to further polish contigs before filling.

Mengyang

**Comment by yangchouxianyu** [comment]
Thank you for your answer.
