### ISSUE TITLE
getopt error for --minmap_arg and its options

### ISSUE THREAD

**Issue by ChathumadaviE** [BGI-Qingdao/TGS-GapCloser#68]
Hi 
I'm running TGS-GapCloser for the first time and I kept the minimap folder which comes with the github clone and updated it according to the manual. 
This is what I ran for tgsgapcloser command:
`tgsgapcloser --scaff Etexanagenome.fasta --reads ZZcleanreads.fasta --output gap_filled_Etexana --ne --tgstype pb --minmap_arg '-x asm20' > pipe.log 2>pipe.err`

It seems like the command is running although the output files haven't been updated after the minimap2.04.log file and the .paf file is empty. What is the usual wait time for mapping?

Here's the output files generated from the command:
-rw-r--r--  1 cue1 domain users  253 Aug 11 09:58 pipe.err
-rw-r--r--  1 cue1 domain users  116 Aug 11 09:58 gap_filled_Etexana.seq_split.log
-rw-r--r--  1 cue1 domain users 117M Aug 11 09:58 gap_filled_Etexana.contig
-rw-r--r--  1 cue1 domain users 3.6K Aug 11 09:58 gap_filled_Etexana.orignial_scaff_infos
-rw-r--r--  1 cue1 domain users  972 Aug 11 09:58 gap_filled_Etexana.name_map
-rw-r--r--  1 cue1 domain users  982 Aug 11 09:58 pipe.log
-rw-r--r--  1 cue1 domain users    0 Aug 11 09:58 gap_filled_Etexana.fill.paf
-rw-r--r--  1 cue1 domain users  425 Aug 11 10:00 gap_filled_Etexana.minimap2.04.log

When I opened the pipe.err file it had the following error:

> getopt: unrecognized option '--minmap_arg'
getopt: invalid option -- 'x'
getopt: invalid option -- ' '
getopt: invalid option -- 'a'
getopt: invalid option -- 's'
getopt: invalid option -- 'm'
getopt: invalid option -- '2'
getopt: invalid option -- '0'

Is this normal? How can I fix this error?

Thanks

**Comment by cchd0001** [comment]
Hi,

I tested your command but no error occurs.
```
./tgsgapcloser --scaff Etexanagenome.fasta --reads ZZcleanreads.fasta --output gap_filled_Etexana --ne --tgstype pb --minmap_arg '-x asm20'
INFO  :   Run tgsgapcloser. from . ;
          Version : 1.2.1 ;
          Release time : 2022-12-30 .


INFO  :   Parsing args starting ...
             --scaff Etexanagenome.fasta
             --reads ZZcleanreads.fasta
             --output gap_filled_Etexana
             --ne
             --tgstype pb
          --minmap_arg -x asm20

INFO  :   Parsing args end .

```
I guess, this maybe some shell incompatible issue,  could your please test 

```/bin/bash ./tgsgapcloser --scaff Etexanagenome.fasta --reads ZZcleanreads.fasta --output gap_filled_Etexana --ne --tgstype pb --minmap_arg '-x asm20'```

Best  wishes
Lidong Guo

**Comment by ChathumadaviE** [comment]
Hi,

Thanks for your response. 

I ran it this time with /bin/bash/ and generated the .fill.paf file and then gave an error:
`[cue1@arccjr TGS-GapCloser-1.2.1]$ cat pipe.err
./tgsgapcloser: line 626: 1752968 Killed                  $MiniMap2 $MINIMAP2_PARAM -t $THREAD $FINAL_READS $TMP_INPUT_SCAFTIG > $OUT_PREFIX.fill.paf 2> $OUT_PREFIX.minimap2.04.log
`
Is this a memory issue?

Thanks!

**Comment by cchd0001** [comment]
Yes, this is the known memory issue, please check https://github.com/BGI-Qingdao/TGS-GapCloser/issues/49 and https://github.com/BGI-Qingdao/TGS-GapCloser/issues/42 for more details.

**Comment by JhinAir** [comment]
Hi, this error is due to the tgsgapcloser version. I tried to install tgsgapcloser by 'conda install -c bioconda tgsgapcloser', but it defaultly installed v1.0.3, in which '--minmap_arg' is not supported. I'm confused why this happened as I can install v1.2.1 in another server. My python version is 3.10 and conda is 23.5.2. Do you know how to solve this please? @cchd0001 Thank you!
Jing

**Comment by JhinAir** [comment]
通过make安装时会发现MakeFile中的‘cp -r tgsgapcloserbin ${PREFIX}/bin’tgsgapcloserbin在安装包中找不到

**Comment by cchd0001** [comment]
请直接运行make 而不是make condainstall
