### ISSUE TITLE
Pilon does not work within tgsgapclpser

### ISSUE THREAD

**Issue by adlyabdalla** [BGI-Qingdao/TGS-GapCloser#69]
I tried to use the tsggapcloser with pacbio  and illumina reads with the following run

tgsgapcloser --scaff /work/CPB/PacBio_sequence/lordec_results/SPAdea_assembly_indo2/scaffolds.fasta --reads /work/CPB/PacBio_sequence/lordec_results/IPCL_S2M_pacbio-corrected_unclassified.fasta --output /home/adly/Desktop/TGS_gapcloser/output_tgsgaplcoser_S2M --ngs /work/CPB/NG-28892_CPB_20211126_lib548024_7771_2__1_trimmed_unclassified.fastq --ngs /work/CPB/NG-28892_CPB_20211126_lib548024_7771_2__2_trimmed_unclassified.fastq --pilon /usr/bin/pilon --samtools /usr/bin/samtools --java /usr/bin/java --tgstype pb  --thread 24 --pilon_mem 500G --p_round 10 

However I noticed that the final expected files are not found and the file is empty. I had a look on the tgsgapcloser sceript and found that the following step was failed

=====================================
print_info_line  "   -   iteration $round chunk $i -  run pilon ... "
                    $JAVA -Xmx$PILON_MEM -jar  $PILON --fix all \
                        --genome $OUT_PREFIX.ont.$curr_tag.fasta --bam $OUT_PREFIX.sort.bam \
                        --output $OUT_PREFIX.ont.$curr_tag.pilon --outdir ./ \
                        --diploid  --threads $THREAD >$OUT_PREFIX.$curr_tag.pilon.log 2>$OUT_PREFIX.pilon.$curr_tag.err || exit 1
                    # remove used bam
                    rm $OUT_PREFIX.sort.bam

                done
                print_info_line "   -   iteration $round end. "
            done
            date >>'done_step_3.B.1_tag'
==========================================

Can you kindly advise on how to fix this issue
Best regards
Adly

**Comment by adlyabdalla** [comment]
These mainly are the files produced by the run
adly@bioanntu:~/Desktop/TGS_29082023$ ls -rtl
total 17220107
-rw-rw-r-- 1 adly adly         196 Aug 29 11:39 output_tgs_S2M.seq_split.log
-rw-rw-r-- 1 adly adly  1062685678 Aug 29 11:40 output_tgs_S2M.contig
-rw-rw-r-- 1 adly adly   249636153 Aug 29 11:40 output_tgs_S2M.orignial_scaff_infos
-rw-rw-r-- 1 adly adly   251671378 Aug 29 11:40 output_tgs_S2M.name_map
-rw-rw-r-- 1 adly adly       81238 Aug 29 11:43 output_tgs_S2M.minimap2.01.log
-rw-rw-r-- 1 adly adly    68521657 Aug 29 11:44 output_tgs_S2M.ont.fasta
-rw-rw-r-- 1 adly adly       10852 Aug 29 11:44 output_tgs_S2M.cand.log
-rw-rw-r-- 1 adly adly    22877708 Aug 29 11:44 output_tgs_S2M.ont.0.0.fasta
-rw-rw-r-- 1 adly adly    22929229 Aug 29 11:44 output_tgs_S2M.ont.0.1.fasta
-rw-rw-r-- 1 adly adly    22714720 Aug 29 11:44 output_tgs_S2M.ont.0.2.fasta
-rw-rw-r-- 1 adly adly    71031236 Aug 29 11:44 output_tgs_S2M.mmi
-rw-rw-r-- 1 adly adly         632 Aug 29 11:44 output_tgs_S2M.minimap2.02.0.0.log
-rw-rw-r-- 1 adly adly        6183 Aug 29 11:57 output_tgs_S2M.minimap2.03.0.0.log
-rw-rw-r-- 1 adly adly           0 Aug 29 12:01 output_tgs_S2M.samtool_01.0.0.log
-rw-rw-r-- 1 adly adly          64 Aug 29 12:06 output_tgs_S2M.samtool_02.0.0.log
-rw-rw-r-- 1 adly adly 15854624299 Aug 29 12:11 output_tgs_S2M.sort.bam
-rw-rw-r-- 1 adly adly           0 Aug 29 12:11 output_tgs_S2M.samtool_03.0.0.log
-rw-rw-r-- 1 adly adly      525216 Aug 29 12:12 output_tgs_S2M.sort.bam.bai
-rw-rw-r-- 1 adly adly          49 Aug 29 12:12 output_tgs_S2M.pilon.0.0.err
-rw-rw-r-- 1 adly adly           0 Aug 29 12:12 output_tgs_S2M.0.0.pilon.log
-rw-rw-r-- 1 adly adly           0 Aug 29 13:34 output_tgs_S2M.ont.0.2.pilon.log
-rw-rw-r-- 1 adly adly         140 Aug 29 13:34 output_tgs_S2M.ont.0.2.pilon.err

**Comment by cchd0001** [comment]
Could you please provide the content of file `output_tgs_S2M.ont.0.2.pilon.err ` ?
