### ISSUE TITLE
TGS-GapCloser：tgsgapcloser: line 374:  1545 Aborted

### ISSUE THREAD

**Issue by suying77** [BGI-Qingdao/TGS-GapCloser#71]
Running tgsgapcloser gives the above error, is there any way to fix it?Thanks

**Comment by suying77** [comment]
tgsgapcloser: line 374:  1545 Aborted $Candidate --ont_reads_a $TGS_READS --contig2ont_paf $OUT_PREFIX.sub.paf --candidate_max 10 --candidate_shake_filter --candidate_merge < $TMP_INPUT_SCAFF_INFO > $OUT_PREFIX.ont.fasta 2> $OUT_PREFIX.cand.log

**Comment by suying77** [comment]
And this command will always be killed：tgsgapcloser: line 374: 45604 Killed                  $Candidate --ont_reads_a $TGS_READS --contig2ont_paf $OUT_PREFIX.sub.paf --candidate_max 10 --candidate_shake_filter --candidate_merge < $TMP_INPUT_SCAFF_INFO > $OUT_PREFIX.ont.fasta 2> $OUT_PREFIX.cand.log

**Comment by cchd0001** [comment]
A known "huge memory issue" may happen in this step, please try our latest codes.

**Comment by suying77** [comment]
Thank you

Lidong ***@***.***> 于2023年9月26日周二 21:55写道：
