### ISSUE TITLE
ERROR: line 645: 16242 Aborted  (core dumped)

### ISSUE THREAD

**Issue by Bank-tidy** [BGI-Qingdao/TGS-GapCloser#74]
Dear Developer,

Thank you for creating this practical software. I've encountered a memory issue while using it and would like to consult you. Here is my code:

```
tgsgapcloser \
    --scaff 100k_Chr7.fasta \
    --reads hifi.fasta \
    --output result_hifi \
    --minmap_arg '-ax map-hifi -t 10 -K 80M' \
    --thread 30 \
    --ne \
    >pipe.log 2>pipe.err
```
Initially, I input the complete genome sequence. The pipe.error file displays:

`tgsgapcloser: line 645: 16242 Aborted                 (core dumped)$GapCloser --ont_reads_a $FINAL_READS --contig2ont_paf $OUT_PREFIX.fill.paf --min_match=$MIN_MATCH --min_idy=$MIN_IDY --prefix $OUT_PREFIX > $OUT_PREFIX.fill.log 2>&1`

Following your suggestion of 5.5Gb xxx.paf records a 32Gb peak memory, I extracted the chromosome 7 genome with gap regions, resulting in a paf file of only 6.8G. My server has 512G of running memory, but I still encounter an error:

`tgsgapcloser: line 645: 16242 Aborted                 (core dumped)$GapCloser --ont_reads_a $FINAL_READS --contig2ont_paf $OUT_PREFIX.fill.paf --min_match=$MIN_MATCH --min_idy=$MIN_IDY --prefix $OUT_PREFIX > $OUT_PREFIX.fill.log 2>&1`
Should I reduce the -t parameter to 10 and increase the -K parameter to 80M, or do you have any other suggestions?

The additional noteworthy point is that in the hifi.fill.log, it shows: "tgsgapcloser: ../biocommon/align_common/align_result.cpp:134: void BGIQD::ALIGN_COMMON::ExtraInfo::InitFromStr(const string&): Assertion `items.size() == 3' failed."

Here is my log screenshot
![image](https://github.com/BGI-Qingdao/TGS-GapCloser/assets/108465040/2599cc73-8e0f-4c94-bcc1-c9997b4c5741)
![image](https://github.com/BGI-Qingdao/TGS-GapCloser/assets/108465040/af9f8d43-cd07-40d0-99c4-01ff06a8023d)
![image](https://github.com/BGI-Qingdao/TGS-GapCloser/assets/108465040/520b45e1-ed5e-46d7-a826-3649c352fca4)
 
Best regards！

**Comment by cchd0001** [comment]
Could you please provide the head 1000 line of tomato_hifi.fill.paf ?

**Comment by Bank-tidy** [comment]
Of course, but this file is a bit big. The first 10 lines of the file have reached 70M. If it is convenient, I can send it to you by email?
![image](https://github.com/BGI-Qingdao/TGS-GapCloser/assets/108465040/e1a8f02f-04d3-445e-b42d-c897dddd865d)
![image](https://github.com/BGI-Qingdao/TGS-GapCloser/assets/108465040/ede20072-e79a-4fa7-975b-2c52fe0c98f3)

**Comment by Bank-tidy** [comment]
@cchd0001 Of course, thank you,but this file is a bit big. The first 10 lines of the file have reached 70M. If it is convenient, I can send it to you by email?
![image](https://github.com/BGI-Qingdao/TGS-GapCloser/assets/108465040/4ba4481c-7e05-4029-b9d9-40de41997c98)
![image](https://github.com/BGI-Qingdao/TGS-GapCloser/assets/108465040/3ffc3806-b50a-4a0d-a7c5-b273f4666d88)

**Comment by cchd0001** [comment]
Oh, please do not use``` -a``` for minimap2 because it set the output format as SAM ( but we expect PAF ).

Please change 

 ```--minmap_arg '-ax map-hifi -t 10 -K 80M'```

to 

 ```--minmap_arg '-x map-hifi -t 10 -K 80M'```

**Comment by Bank-tidy** [comment]
@cchd0001  Oh, I understand, thank you for your answer!
