### ISSUE TITLE
How to check the correctness of filling gaps?

### ISSUE THREAD

**Issue by luca-Wang** [BGI-Qingdao/TGS-GapCloser#75]
Hello, my genome has 10G and contains 500 gaps. After running the tgs-gapcloser software, I successfully filled 90 gaps. May I ask how to check the correctness of filling these gaps one by one? 
I used IGV software to check， whether there is a quick way to identify reads that support each gap and verify their correctness？

Thanks in advance!

**Comment by adonis316** [comment]
If you have a reference genome for this species or closely related species, then you can align and compare these closed gaps with the reference using minimap2.

If this is a de novo project without any reference genome, then checking the alignments of reads to the gap region is a fast but efficient measure to check the correctness. You can directly analyze the alignment file in SAM/PAF format. Plus, IGV is a good option to visualize these alignments.

Thanks,
Mengyang
