### ISSUE TITLE
TGS reads input

### ISSUE THREAD

**Issue by Hanjiangna** [BGI-Qingdao/TGS-GapCloser#83]
Can TGS reads, which are originally in FASTQ format generated from ONT (Oxford Nanopore Technologies) or HiFi (PacBio HiFi) sequencing, be converted to FASTA format and used as input for further analysis?

**Comment by cchd0001** [comment]
Yes, of course you can.
We always can convert FASTQ to FASTA by simply dropping the quality data and modifying ```@``` to ```>``` .

**Comment by Hanjiangna** [comment]
Thank you for your prompt response.
Best wishes
Hanjiangna
