### ISSUE TITLE
Candidate aborts with an error

### ISSUE THREAD

**Issue by felixgrewe** [BGI-Qingdao/TGS-GapCloser#9]
I want to close gaps in SSPACE-Longread scaffolds of a wtbdg2 nanopore assembly (no Illumina polishing possible).

When I run TGS-GapCloser without error correction (--ne) it finished, but when I use error correction with racon it stoped at step 2.2:

**pipe.err**
[...]
TGS-GapCloser.sh: line 373: 113308 Aborted                 (core dumped) $Candidate --ont_reads_a $TGS_READS --contig2ont_paf $OUT_PREFIX.sub.paf --candidate_max 10 --candidate_shake_filter --candidate_merge < $TMP_INPUT_SCAFF_INFO > $OUT_PREFIX.ont.fasta 2> $OUT_PREFIX.cand.log

**<name>.cand.log**
[...]
TGSGapCandidate	INFO	CST	2020/4/28	1:7:26	:	LoadPAF finish. used wall clock : 217 seconds, cpu time : 217.104172 seconds
TGSGapCandidate	INFO	CST	2020/4/28	1:7:26	:	LoadScaffInfo start now ... 
TGSGapCandidate	INFO	CST	2020/4/28	1:7:31	:	LoadScaffInfo finish. used wall clock : 5 seconds, cpu time : 5.176731 seconds
TGSGapCandidate	INFO	CST	2020/4/28	1:7:31	:	ParseAllGap start now ... 
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at

**Comment by adonis316** [comment]
Hi,
We have seen this error when the input TGS long reads are in fastq format before.
Would you please provide us your whole command (TGS-GapCloser.sh. XXXXXXX)?

**Comment by felixgrewe** [comment]
Thanks for you immediate help. 

Yes, I have an wtdbg2 assembly of nanopore only reads, used then SSPACE-Longread for scaffolding, and tried to close gaps with TGS-GapCloser. 

Regarding your suggestions: 1) I should have a mean coverage of 50x. 2) Thank you for this suggestion, I'll continue this route.

~/git/TGS-GapCloser/TGS-GapCloser.sh  \
        --scaff  <path-to>/scaffolds.fasta \
        --reads  <path-to>/<ont-reads>.fastq \
        --output wtbdg2-SSPACE \
        --racon <path-to>/bin/racon \
        >pipe.log 2>pipe.err

**Comment by adonis316** [comment]
The input long reads should be in FASTA format.  Please convert your ONT reads from FASTQ to FASTA first. Let me if it works for you.
