### ISSUE TITLE
Nanopore reads adaptor

### ISSUE THREAD

**Issue by Zhenlisme** [BGI-Qingdao/TGS-GapCloser#90]
Hello,

I would like to know:
1) if I need to trim the adaptor of nanopore reads before running TGS-Gapcloser. 
2) can TGS-Gapcloser distinguish different subgenomes of allotetraploids ?

Thank you for your help.

**Comment by cchd0001** [comment]
Please trim the adaptor.

TGS-Gapcloser has no specific design for polyploid, thus we can not guarantee the correctness.

**Comment by Zhenlisme** [comment]
Thank  you for your help.
